# Generated by Django 3.0.7 on 2020-06-07 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.Options')),
                ('option_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='option_a', to='quiz.Options')),
                ('option_b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='option_b', to='quiz.Options')),
                ('option_c', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='option_c', to='quiz.Options')),
                ('option_d', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='option_d', to='quiz.Options')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
