# Generated by Django 3.0.7 on 2020-06-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_d',
        ),
    ]
